language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements/requirements.txt -r requirements/requirements-dev.txt -r requirements/requirements-features.txt coveralls
script:
  - pytest --cov=cincoconfig --cov-report=term-missing
  - pycodestyle cincoconfig
  - pylint --rcfile=.pylintrc cincoconfig
  - mypy cincoconfig
after_success:
 coveralls
