[tool.pdm.build]
includes = ["cincoconfig/VERSION"]

[project]
# PEP 621 project metadata
# See https://www.python.org/dev/peps/pep-0621/
authors = [
    {name = "Adam Meily", email = "meily.adam@gmail.com"},
]
license = {text = "ISC"}
requires-python = "<4.0,>=3.7"
dependencies = []
name = "cincoconfig"
version = "0.9.0"
description = "Universal configuration file parser"
readme = "README.md"
keywords = ["config", "configuration"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: ISC License (ISCL)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Application Frameworks"
]

[project.urls]
repository = "https://github.com/ameily/cincoconfig"
documentation = "https://cincoconfig.readthedocs.io/en/latest/"

[dependency-groups]
dev = [
    "ruff<1.0.0,>=0.0.261",
    "pyright<2.0.0,>=1.1.302",
    "sphinx",
    "sphinx-autodoc-typehints<2.0,>=1.22",
    "sphinx-rtd-theme<2.0.0,>=1.2.0",
    "coverage<8.0.0,>=7.2.3",
    "pytest<8.0.0,>=7.3.0",
    "black<24.0.0,>=23.3.0",
]
bson = [
    "bson",
]
yaml = [
    "pyyaml",
]
crypto = [
    "cryptography",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.ruff]
select = ["E", "F", "I"]
line-length = 99


[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
    "raise NotImplementedError",
    "if __name__ == .__main__.:"
]

[tool.pdm.scripts]
"build-docs" = { cmd = "sphinx-build docs docs/_build" }
"check-format" = { composite = [
    "black --check cincoconfig tests",
    "ruff check --select I cincoconfig"
]}

"check-typing" = { cmd = "pyright cincoconfig" }
checks = { composite = [
    "check-format",
    "lint",
    "check-typing"
]}
ci = { composite = [
    "checks",
    "tests",
    "build-docs"
]}
format = { composite = [
    "black cincoconfig tests",
    "ruff --select I --fix --exit-zero cincoconfig"
]}
lint = { cmd = "ruff --select E,F cincoconfig" }
tests = { composite = [
    "coverage run --source cincoconfig -m pytest",
    "coverage report -m"
]}
# The check-spelling task is currently disabled until poe fixes CMD resolution on Windows:
# https://github.com/nat-n/poethepoet/pull/142
# "check-spelling" = "npx cspell \"cincoconfig/**/*.py\" \"docs/*.rst\" CHANGELOG.md"
