name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage coveralls ruff pyright
      - name: Linting
        run: |
          ruff check cincoconfig
          pyright cincoconfig
      - name: Test with pytest
        run: |
          pytest --cov=cincoconfig --cov-report=term-missing
          coveralls
